### ISSUE TITLE
tenantInfo is not passed into DBContext

### ISSUE THREAD

**Issue by Glebby** [Finbuckle/Finbuckle.MultiTenant#194]
Hi there, I am trying to set up multitenancy in my project (.Net Core 2.2), but no matter what I do, the tenantInfo is always null in my DbContext constructor.  My DBContext class inherits from MultiTenantIdentityDbContext<ApplicationUser>.

I use StaticStrategy and In-Memory store to simplify tings and isolate the issue, and I can see that TenantInfo is set as expected by examining GetMultiTenantContext().TenantInfo in the view. 

As a result (or at least I think these problems are connected), I get NullReferenceException every time when an operation on the dbContext is invoked 

Example:
Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__21`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.UserManager`1.<FindByNameAsync>d__78.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SQLwallet.Controllers.AccountController.<Login>d__19.MoveNext() in AccountController.cs:line 208

Appreciate any help. The library looks very promising if only I could get it working :)

Regards
Gleb

**Comment by AndrewTriesToCode** [comment]
Hi @Glebby 

I’m sure we can figure it out. Can you post your ConfigureServices and Configure methods?
