### ISSUE TITLE
Why the tenant is not found?

### ISSUE THREAD

**Issue by win32nipuh** [Finbuckle/Finbuckle.MultiTenant#257]
That is my  ConfigureServices
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IConfiguration>(Configuration);
            services.AddFeatureManagement();
            services.AddMultiTenant<TenantInfo>()
                .WithConfigurationStore()
                .WithHostStrategy("__tenant__.*");
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddHttpContextAccessor();
            services.AddDbContext<ToDoDbContext>();
        }

```
There is my appsettings.json section
```
  "Finbuckle:MultiTenant:Stores:ConfigurationStore": {
    "Defaults": {
      "ConnectionString": "Data Source=Data/ToDoList.db"
    },
    "Tenants": [
      {
        "Id": "localhost",
        "Identifier": "localhost",
        "Name": "Localhost",
        "ConnectionString": "Data Source=Data/ToDoList.db"
      },
      {
        "Id": "sme1",
        "Identifier": "megacorp",
        "Name": "MegaCorp",
        "ConnectionString": "Data Source=Data/ToDoList.db"
      },
      {
        "Id": "sme2",
        "Identifier": "sme2",
        "Name": "Finbuckle",
        "ConnectionString": "Data Source=Data/ToDoList.db"
      },
      {
        "Id": "bigcorp",
        "Identifier": "initech",
        "Name": "Initech GmBH",
        "ConnectionString": "Data Source=Data/Initech_ToDoList.db"
      }
    ]
  },

```
When I run  the app I receive the exception. What is incorrect?

```
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:5001
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5000
Finbuckle.MultiTenant.Strategies.HostStrategy.GetIdentifierAsync: Found identifier: "localhost".
Finbuckle.MultiTenant.Stores.ConfigurationStore: Information: Finbuckle.MultiTenant.Stores.ConfigurationStore`1[Finbuckle.MultiTenant.TenantInfo].TryGetByIdentifierAsync: Tenant found with identifier "localhost".
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
'PMTF.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Diagnostics.StackTrace.dll'. 
'PMTF.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Reflection.Metadata.dll'. 
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'Boolean Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer.HasDifferences(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Metadata.IModel)'.
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
'PMTF.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.2\Microsoft.AspNetCore.Http.Extensions.dll'. 
'PMTF.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.2\Microsoft.AspNetCore.WebUtilities.dll'. 
'PMTF.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Net.WebSockets.dll'. 
Finbuckle.MultiTenant.Strategies.HostStrategy: Information: Finbuckle.MultiTenant.Strategies.HostStrategy.GetIdentifierAsync: Found identifier: "sme2".
Finbuckle.MultiTenant.Stores.ConfigurationStore: Information: Finbuckle.MultiTenant.Stores.ConfigurationStore`1[Finbuckle.MultiTenant.TenantInfo].TryGetByIdentifierAsync: Tenant found with identifier "sme2".
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'Boolean Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer.HasDifferences(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Metadata.IModel)'.
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
'PMTF.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.2\System.Runtime.Intrinsics.dll'. 
Finbuckle.MultiTenant.Strategies.HostStrategy: Information: Finbuckle.MultiTenant.Strategies.HostStrategy.GetIdentifierAsync: Found identifier: "sme2".
Finbuckle.MultiTenant.Stores.ConfigurationStore: Information: Finbuckle.MultiTenant.Stores.ConfigurationStore`1[Finbuckle.MultiTenant.TenantInfo].TryGetByIdentifierAsync: Tenant found with identifier "sme2".
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'Boolean Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer.HasDifferences(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Metadata.IModel)'.
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Finbuckle.MultiTenant.Strategies.HostStrategy: Information: Finbuckle.MultiTenant.Strategies.HostStrategy.GetIdentifierAsync: Found identifier: "sme2".
Finbuckle.MultiTenant.Stores.ConfigurationStore: Information: Finbuckle.MultiTenant.Stores.ConfigurationStore`1[Finbuckle.MultiTenant.TenantInfo].TryGetByIdentifierAsync: Tenant found with identifier "sme2".
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'Boolean Microsoft.EntityFrameworkCore.Migrations.IMigrationsModelDiffer.HasDifferences(Microsoft.EntityFrameworkCore.Metadata.IModel, Microsoft.EntityFrameworkCore.Metadata.IModel)'.
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
The program '[20608] PMTF.exe' has exited with code -1 (0xffffffff).


```

**Comment by AndrewTriesToCode** [comment]
@win32nipuh Can you also post your `Configure` method in the `Startup` class?

This looks like a problem with EFCore migrations-- it is probably trying to create an instance of your db context for migration purposes but can't do so because there is no tenant for this request.

Do you plan to run migrations from the command line or let the application handle it?

Either way special consideration are needed. I prefer design time factory for migration. I probably need to document migrations with this library better - https://www.finbuckle.com/MultiTenant/Docs/EFCore#design-time-instantiation

I recommend you look at IdentityDataIsolation sample source code to see the design time factory I have there for migrations to use.

**Comment by Oleg26Dev** [comment]
If honestly I do not want to do any migrations.
At least I want to run this example in a Blazor.
Ok, I will try to use v6 and will see how it works.
