### ISSUE TITLE
How to read the configuration from a separate file?

### ISSUE THREAD

**Issue by ZedZipDev** [Finbuckle/Finbuckle.MultiTenant#277]
Now the configuration is in the appsettings.json file in the section:
"Finbuckle:MultiTenant:Stores:ConfigurationStore"

Is it possible to use a separate file for the "Finbuckle:MultiTenant:Stores:ConfigurationStore"?

I pack my app to the Docker image and it may be useful to locate the config file in a mapped  folder to provide user possibility to edit the configuration.

I have made: moved the section
"Finbuckle:MultiTenant:Stores:ConfigurationStore"
to the appsettings2.json file
```
           var config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .AddJsonFile(@"..\Config\appsettings2.json", optional: true)
                .Build();

```

```
services.AddMultiTenant<DerivedTenantInfo>()
                    .WithStore<ConfigurationStore<DerivedTenantInfo>>(ServiceLifetime.Singleton)
                    .WithHostStrategy(tenantSettings.HostTemplate)
                    .WithPerTenantOptions<S3ConfigOptions>((options, tenantInfo) =>
                    {
                        options.ServiceURL = tenantInfo.S3ServiceURL;
                    });


```
But when I run the app it gives an exception:
```
Finbuckle.MultiTenant.MultiTenantException: Section name provided to the Configuration Store is invalid.
   at Finbuckle.MultiTenant.Stores.ConfigurationStore`1..ctor(IConfiguration configuration, String sectionName)
   at Finbuckle.MultiTenant.Stores.ConfigurationStore`1..ctor(IConfiguration configuration)

```

**Comment by AndrewTriesToCode** [comment]
@Oleg26Dev you can use another file: see the general file configuration provider info here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#file-configuration-provider

In fact you can use any ASP.NET Core configuration provider or a custom one: database, environment variables, secret store... anything really.

**Comment by AndrewTriesToCode** [comment]
Do you still get an error if you use `WithConfigurationStore()` instead of `WithStore<...>()`? Also can you post your `Program.cs` file where the host is configured?

**Comment by win32nipuh** [comment]
That is Program.cs
```
        public static void Main(string[] args)
        {
            bool btodo = true;
            var host = CreateHostBuilder(args).Build();

            //const string environment = "Production";

            //var config = new ConfigurationBuilder()
            //    .AddJsonFile("appsettings.json")
            //    .AddJsonFile($"appsettings.{environment}.json", optional: true)
            //    .Build();


            var config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .AddJsonFile(@"..\Config\appsettings2.json", optional: true)
                .Build();

            Console.WriteLine("RouteStrategy: " + config["TenantStrategy:RouteStrategy"]);
            Console.WriteLine("Identifier:          " + config["Identifier"]);
            Console.WriteLine("Connection String " + config["ConnectionString"]);

            // Set up the databases for the sample if needed.
            var env = host.Services.GetService<IWebHostEnvironment>();
            if (env.EnvironmentName == "Development" && btodo)
            {
                
                using (var db = new ToDoDbContext(new DerivedTenantInfo { ConnectionString = "Data Source=Data/ToDoList.db" }))
                {
                    db.Database.MigrateAsync().Wait();
                }

                using (var db = new ToDoDbContext(new DerivedTenantInfo { ConnectionString = "Data Source=Data/Initech_ToDoList.db" }))
                {
                    db.Database.MigrateAsync().Wait();
                }
                using (var db = new ToDoDbContext(new DerivedTenantInfo { ConnectionString = "Data Source=Data/Local_ToDoList.db" }))
                {
                    db.Database.MigrateAsync().Wait();
                }

                using (var db = new ToDoDbContext(new DerivedTenantInfo { ConnectionString = "Data Source=Data/FB_ToDoList.db" }))
                {
                    db.Database.MigrateAsync().Wait();
                }
            }

            host.Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }


```

**Comment by AndrewTriesToCode** [comment]
Hello @Oleg26Dev Thanks for the details. Two things:

1) The path to your json file should be `@".\Config\appsettings2.json"` (only a single leading dot) based on your folder configuration.

2) You create a config in `Main`, but that is a totally separate configuration from the one ASP.NET Core creates and uses. To add your json file to the built-in configuration call `ConfigureAppConfiguration` as a part of your `CreateHostBuilder` method:
```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(config =>
                {
                    config.AddJsonFile(@"./Config/appsettings2.json");
                    //Console.WriteLine(....);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

Give that a try, that should get you going. I was able to run the app like that.
