### ISSUE TITLE
InvalidOperationException: Cannot consume scoped service

### ISSUE THREAD

**Issue by dwt12777** [Finbuckle/Finbuckle.MultiTenant#305]
Not sure if this is the same issue as #278 but I'm getting a similar error in my project.  I feel like I'm on the verge of greatness, but can't seem to figure this out.  I should point out **I get this identical error when I try to build and run the EFCoreStoreSample project.**

```
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Finbuckle.MultiTenant.ITenantResolver`1[Finbuckle.MultiTenant.TenantInfo] Lifetime: Singleton ImplementationType: Finbuckle.MultiTenant.TenantResolver`1[Finbuckle.MultiTenant.TenantInfo]': Cannot consume scoped service 'System.Collections.Generic.IEnumerable`1[Finbuckle.MultiTenant.IMultiTenantStore`1[Finbuckle.MultiTenant.TenantInfo]]' from singleton 'Finbuckle.MultiTenant.ITenantResolver`1[Finbuckle.MultiTenant.TenantInfo]'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at EFCoreStoreSample.Program.Main(String[] args) in F:\Source\Finbuckle.MultiTenant\samples\ASP.NET Core 3\EFCoreStoreSample\Program.cs:line 10

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Finbuckle.MultiTenant.ITenantResolver`1[Finbuckle.MultiTenant.TenantInfo] Lifetime: Singleton ImplementationType: Finbuckle.MultiTenant.TenantResolver`1[Finbuckle.MultiTenant.TenantInfo]': Cannot consume scoped service 'System.Collections.Generic.IEnumerable`1[Finbuckle.MultiTenant.IMultiTenantStore`1[Finbuckle.MultiTenant.TenantInfo]]' from singleton 'Finbuckle.MultiTenant.ITenantResolver`1[Finbuckle.MultiTenant.TenantInfo]'.

Inner Exception 2:
InvalidOperationException: Cannot consume scoped service 'System.Collections.Generic.IEnumerable`1[Finbuckle.MultiTenant.IMultiTenantStore`1[Finbuckle.MultiTenant.TenantInfo]]' from singleton 'Finbuckle.MultiTenant.ITenantResolver`1[Finbuckle.MultiTenant.TenantInfo]'.
```

The project builds successfully, but when the site tries to run the exception is thrown and the debugger points at the line `CreateHostBuilder(args).Build().Run();` in my Program.cs file:

```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace EFCoreStoreSample
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```

If it helps, here are the contents of my Startup.cs file:

```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using ReardenNews.Web.Data;

namespace ReardenNews.Web
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            
            services.AddDbContext<AppDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("ReardenNewsDb"))
                );

            services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true).AddEntityFrameworkStores<AppDbContext>();

            services.AddRazorPages();

            services.Configure<RouteOptions>(options =>
            {
                options.ConstraintMap.Add("PageModeEnum", typeof(PageModeRouteConstraint));
            });

            services.AddMultiTenant<ReardenTenantInfo>()
               .WithHostStrategy("*.__tenant__.?")
               .WithStaticStrategy("localhost")
               .WithEFCoreStore<AppDbContext, ReardenTenantInfo>()
               .WithPerTenantAuthentication();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseRouting();
            app.UseMultiTenant();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        }
    }
}
```
Thanks again for all your help!

**Comment by AndrewTriesToCode** [comment]
It’s the same issue and I have fixed it but not yet released. I’ll post a code fix you can do shortly.

**Comment by dwt12777** [comment]
Awesome - thank you!

**Comment by AndrewTriesToCode** [comment]
As a workaround after your call to `AddMultiTenant<T>()` and its chained builders add these two lines:

```cs
services.Replace(new ServiceDescriptor(typeof(ITenantResolver<TenantInfo>), typeof(TenantResolver<TenantInfo>), ServiceLifetime.Scoped));
services.Replace(new ServiceDescriptor(typeof(ITenantResolver), sp => sp.GetRequiredService<ITenantResolver<TenantInfo>>(), ServiceLifetime.Scoped));
```

They might require some `using` statements to pull in the right namespace and of course sub in your own class for `TenantInfo` if you aren't using the default one.

**Comment by dwt12777** [comment]
This seems to be working great!  Thank you.  One problem down and now the next manifests itself... I'll log a separate question if I can't figure it out.  Thanks again for your support!
