### ISSUE TITLE
EF Migration fails with custom Identity user

### ISSUE THREAD

**Issue by LearnGrowAndShare** [Finbuckle/Finbuckle.MultiTenant#333]
Hi, 
I followed the documentation to integrate the Multi-Tenancy for Identity server 4 with ASP.NET Core Identity
> https://www.finbuckle.com/MultiTenant/Docs/Identity

Also referred the sample for ASP.NET Core Identity

> https://github.com/Finbuckle/Finbuckle.MultiTenant/tree/master/samples/ASP.NET%20Core%203/IdentityDataIsolationSample

It works well if I use IdentityUser, but when I switch to a class extending the IdentityUser the migration fails to happen 

Identity User - 
```
    [MultiTenant]
    public class ApplicationUser : IdentityUser
    {
        public bool IsEnabled { get; set; }
        public string TenantId { get; set; }
    }
```

Identity context - 
```
 public class IdentityDbContext : MultiTenantIdentityDbContext<ApplicationUser>
    {
        public IdentityDbContext(ITenantInfo tenantInfo) : base(tenantInfo)
        {
        }

        public IdentityDbContext(ITenantInfo tenantInfo, DbContextOptions<IdentityDbContext> options)
            : base(tenantInfo, options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // builder.Entity<ApplicationUser>().IsMultiTenant();  


        }
```

Command I use for migration -
 `dotnet ef migrations add MultiTenant -c IdentityDbContext -o Data/Migrations/AspNetIdentity/AspNetIdentityDb`

Error - 
```
System.InvalidOperationException: The seed entity for entity type 'ApplicationUser' cannot be added because there was no value provided for the required property 'TenantId'.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateData(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.NpgsqlModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)

```
**Tried -** 
I tried putting [MultiTenant] over application user or    
  builder.Entity<ApplicationUser>().IsMultiTenant in Db Context s mentioned in documentation, 
Both results in same error.
I tried defining TenantId in ApplicationUser same error :(

If I put both ( _[MultiTenant] and builder.Entity<ApplicationUser>().IsMultiTenant_)  I get below error - 
```
**System.NullReferenceException: Object reference not set to an instance of an object.**
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.RemoveIndex(Index index)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.RemoveIndex(IMutableIndex index)
   at Finbuckle.MultiTenant.EntityFrameworkCore.FinbuckleEntityTypeBuilderExtensions.RemoveIndex(EntityTypeBuilder builder, String propName)
   at Finbuckle.MultiTenant.EntityFrameworkCore.FinbuckleEntityTypeBuilderExtensions.UpdateIdentityUserIndex(EntityTypeBuilder builder)
   at Finbuckle.MultiTenant.EntityFrameworkCore.FinbuckleEntityTypeBuilderExtensions.IsMultiTenant[T](T builder)
```

Any help would be appreciated on how to get the ef migration working :(

**Comment by AndrewTriesToCode** [comment]
Hi @dreamerNcoder 

I think you are close -- at design time there is obviously no "tenant" in the normal sense. See this part of the Docs (about EFCore, not Identity specifically):
[https://www.finbuckle.com/MultiTenant/Docs/EFCore#design-time-instantiation](https://www.finbuckle.com/MultiTenant/Docs/EFCore#design-time-instantiation)

You can see this used in the sample in this file:
[https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/samples/ASP.NET%20Core%203/IdentityDataIsolationSample/Data/DesignTimeFactory.cs](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/master/samples/ASP.NET%20Core%203/IdentityDataIsolationSample/Data/DesignTimeFactory.cs)

I think this will get it working for you.

Best of luck and let me know how it goes.

**Comment by goforebroke** [comment]
Hi Andrew,

I have the same issue when trying to customize the identity model. I have two 

Startup.cs

```
  // Register the db context, but do not specify a provider/connection
            // string since these vary by tenant.
            services.AddDbContext<ApplicationDbContext>();

            services.AddDefaultIdentity<ApplicationUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddMultiTenant<TenantInfo>()
                .WithEFCoreStore<MultiTenantStoreDbContext, TenantInfo>()
                .WithRouteStrategy();
```

ApplicationUser.cs

```
 public class ApplicationUser: IdentityUser
    {
        public string FirstName { get; set; }

        public string MiddleName { get; set; }

        public string LastName{ get; set; }


    }
```

ApplicationDbContext.cs

```
 public class ApplicationDbContext : MultiTenantIdentityDbContext
    {
        public ApplicationDbContext(ITenantInfo tenantInfo) : base(tenantInfo)
        {
        }

        public ApplicationDbContext(ITenantInfo tenantInfo, DbContextOptions<ApplicationDbContext> options) : base(tenantInfo, options)
        {
            //Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(TenantInfo.ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            // set a global query filter, e.g. to support soft delete
            modelBuilder.Entity<Playlist>().HasQueryFilter(p => !p.IsDeleted);
            modelBuilder.Entity<Song>().HasQueryFilter(p => !p.IsDeleted);

            modelBuilder.Entity<Playlist>().IsMultiTenant();
            modelBuilder.Entity<Song>().IsMultiTenant();

            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<ApplicationUser>().IsMultiTenant();
        }

        public DbSet<Playlist> PlayLists { get; set; }
        public DbSet<Song> Songs { get; set; }

        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
    }
```
DesignTimeFactory.cs

```
    public class SharedDesignTimeFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public ApplicationDbContext CreateDbContext(string[] args)
        {
            // To prep each database uncomment the corresponding line below.
            var tenantInfo = new TenantInfo { ConnectionString = "\"Server=(localdb)\\\\MSSQLLocalDB;Database=PlayList;MultipleActiveResultSets=true\"" };
            var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();

            return new ApplicationDbContext(tenantInfo, optionsBuilder.Options);
        }
    }

```
Here is the output error when I try to create a migration.

```
PM> dotnet ef migrations add Initial --context ApplicationDbContext
Build started...
Build succeeded.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.RemoveIndex(Index index)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.Microsoft.EntityFrameworkCore.Metadata.IMutableEntityType.RemoveIndex(IMutableIndex index)
   at Finbuckle.MultiTenant.EntityFrameworkCore.FinbuckleEntityTypeBuilderExtensions.RemoveIndex(EntityTypeBuilder builder, String propName)
   at Finbuckle.MultiTenant.EntityFrameworkCore.FinbuckleEntityTypeBuilderExtensions.UpdateIdentityUserIndex(EntityTypeBuilder builder)
   at Finbuckle.MultiTenant.EntityFrameworkCore.FinbuckleEntityTypeBuilderExtensions.IsMultiTenant[T](T builder)
   at MultiTenantCoreEx1.Data.ApplicationDbContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\Jaime\source\repos\MultiTenantCoreEx1\Data\ApplicationDbContext.cs:line 42
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

If I don't try to customize the identity model, and just use IdentityUser, I can create the migration and update the database.

Any suggestions?

**Comment by AndrewTriesToCode** [comment]
hi @goforebroke 

I think the issue is that `IsMultiTenant` tries to adjust indexes on some identity entities and for some reason it's not working. I'll take a look today.

The current code looks like this and its crashing at first line to remove the index. Did you by chance change the index name? I need to make this work smarter.

Can you post your migration file so I can see how Identity is setting up the database schema?

```cs
        private static void UpdateIdentityUserIndex(this EntityTypeBuilder builder)
        {
            builder.RemoveIndex("NormalizedUserName");
#if NET // Covers .NET 5.0 and later.
            builder.HasIndex("NormalizedUserName", "TenantId").HasDatabaseName("UserNameIndex").IsUnique();
#else   // .NET Core 2.1 and 3.1
            builder.HasIndex("NormalizedUserName", "TenantId").HasName("UserNameIndex").IsUnique();
#endif
        }
```

**Comment by goforebroke** [comment]
Andrew,

The migration file is never created when I try to extend the Identity Model. I have not made any changes to the indexes that are created.

Below is the migration file if I don't try to customize the Identity model

```
 public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AspNetRoles",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    Name = table.Column<string>(maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(nullable: true),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    UserName = table.Column<string>(maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(maxLength: 256, nullable: true),
                    Email = table.Column<string>(maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(nullable: false),
                    PasswordHash = table.Column<string>(nullable: true),
                    SecurityStamp = table.Column<string>(nullable: true),
                    ConcurrencyStamp = table.Column<string>(nullable: true),
                    PhoneNumber = table.Column<string>(nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(nullable: false),
                    TwoFactorEnabled = table.Column<bool>(nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(nullable: true),
                    LockoutEnabled = table.Column<bool>(nullable: false),
                    AccessFailedCount = table.Column<int>(nullable: false),
                    Discriminator = table.Column<string>(nullable: false),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false),
                    FirstName = table.Column<string>(nullable: true),
                    MiddleName = table.Column<string>(nullable: true),
                    LastName = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUsers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "PlayLists",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    IsDeleted = table.Column<bool>(nullable: false),
                    Title = table.Column<string>(nullable: true),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlayLists", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetRoleClaims",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    RoleId = table.Column<string>(nullable: false),
                    ClaimType = table.Column<string>(nullable: true),
                    ClaimValue = table.Column<string>(nullable: true),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoleClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetRoleClaims_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserClaims",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UserId = table.Column<string>(nullable: false),
                    ClaimType = table.Column<string>(nullable: true),
                    ClaimValue = table.Column<string>(nullable: true),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetUserClaims_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserLogins",
                columns: table => new
                {
                    Id = table.Column<string>(nullable: false),
                    LoginProvider = table.Column<string>(nullable: false),
                    ProviderKey = table.Column<string>(nullable: false),
                    ProviderDisplayName = table.Column<string>(nullable: true),
                    UserId = table.Column<string>(nullable: false),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserLogins", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetUserLogins_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserRoles",
                columns: table => new
                {
                    UserId = table.Column<string>(nullable: false),
                    RoleId = table.Column<string>(nullable: false),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserRoles", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserTokens",
                columns: table => new
                {
                    UserId = table.Column<string>(nullable: false),
                    LoginProvider = table.Column<string>(nullable: false),
                    Name = table.Column<string>(nullable: false),
                    Value = table.Column<string>(nullable: true),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
                    table.ForeignKey(
                        name: "FK_AspNetUserTokens_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Songs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    IsDeleted = table.Column<bool>(nullable: false),
                    Artist = table.Column<string>(nullable: true),
                    Title = table.Column<string>(nullable: true),
                    PlaylistId = table.Column<int>(nullable: true),
                    TenantId = table.Column<string>(maxLength: 64, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Songs", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Songs_PlayLists_PlaylistId",
                        column: x => x.PlaylistId,
                        principalTable: "PlayLists",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AspNetRoleClaims_RoleId",
                table: "AspNetRoleClaims",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles",
                columns: new[] { "NormalizedName", "TenantId" },
                unique: true,
                filter: "[NormalizedName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserClaims_UserId",
                table: "AspNetUserClaims",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserLogins_UserId",
                table: "AspNetUserLogins",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserLogins_LoginProvider_ProviderKey_TenantId",
                table: "AspNetUserLogins",
                columns: new[] { "LoginProvider", "ProviderKey", "TenantId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserRoles_RoleId",
                table: "AspNetUserRoles",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                table: "AspNetUsers",
                column: "NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "AspNetUsers",
                columns: new[] { "NormalizedUserName", "TenantId" },
                unique: true,
                filter: "[NormalizedUserName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Songs_PlaylistId",
                table: "Songs",
                column: "PlaylistId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AspNetRoleClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserLogins");

            migrationBuilder.DropTable(
                name: "AspNetUserRoles");

            migrationBuilder.DropTable(
                name: "AspNetUserTokens");

            migrationBuilder.DropTable(
                name: "Songs");

            migrationBuilder.DropTable(
                name: "AspNetRoles");

            migrationBuilder.DropTable(
                name: "AspNetUsers");

            migrationBuilder.DropTable(
                name: "PlayLists");
        }
    }
```

**Comment by AndrewTriesToCode** [comment]
Thanks for the detail. I think I see the root cause.

I noticed here you probably want to inherit from `MultiTenantIdentityDbContext<ApplicationUser>` since you are replacing the existing `IdenitityUser` implementation. You also don't need to add a `DbSet<ApplicationUser>` because when you use the generic base class it adds it for you. This works similarly for regular Identity when you use a custom user class.

I think the way you have it now ends up with both a `IdentityUser` and `ApplicationUser` registered (the former is in the base class).
```cs
public class ApplicationDbContext : MultiTenantIdentityDbContext

// change to
public class ApplicationDbContext : MultiTenantIdentityDbContext<ApplicationUser>
```

Give that a try and let me know.

Also note that while you don't have to add a `DbSet<ApplicationUser>` property you do still need to call `Users.IsMultiTenant()` in `OnModeling`.

**Comment by goforebroke** [comment]
That worked! Thank you very much Andrew

**Comment by mkgn** [comment]
I have the same problem, but not for IdentityUser but for IdentityRole. Below is how I have implemented it so far.
`    
public class ApplicationRole : IdentityRole, IEntity,IFullAuditedEntity,ISoftDelete
    {
        public string TenantId { get; set; }
    }

`

My DbContext goes as;

`
public class ApplicationDbContext : MultiTenantIdentityDbContext<ApplicationUser>{}
`

In Startup I register identity classes as;

`
            services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

`

Note: In above your Identity sample, you have only added services.AddIdentity<IdentityUser>, but in my case there is no method to add only IdentityUser , I always have to add IdentityUser & IdentityRole or any derived class from those

Then I have the model bulders and seeders and a design time factory.

`
IDesignTimeDbContextFactory<ApplicationDbContext>{}
`

Design time factory takes additional parameters (1. which tenant to create the database 2. whether to seed data) from config file.
So, even if I populate my Role  class by filling the tenant Id it complains;

The seed entity for entity type 'ApplicationRole' cannot be added because no value was provided for the required property 'TenantId'.

I debugged the seed area of the code an I can confirm the roles have a tenant specified for TenantID.

What may be the cause?

**Comment by mkgn** [comment]
Got it sorted. It was an overlook from my end. I had to register IdentityUser/IdentityRole properly in MultitenantContext

**Comment by AndrewTriesToCode** [comment]
@mkgn glad you sorted it out. This stuff definitely can get complicated.

**Comment by wmembreno** [comment]
Hello @AndrewTriesToCode thanks, I was struggling with the same issue of @goforebroke, now I'm able to add migrations, I have a question, just by adding this migrations will it keep updated all the databases in the different tenants? or do i have to do any manual work to achieve that goal?

**Comment by AndrewTriesToCode** [comment]
Hello @wmembreno 

Unfortunately multiple databases have to each be migrated to separately. Looping through the MultiTenant store and applying them programmatically is a straight forward way to do so.
