### ISSUE TITLE
add Identity to StoreDbContext

### ISSUE THREAD

**Issue by solopromiguel** [Finbuckle/Finbuckle.MultiTenant#465]
I'm trying to add Identity to StoreDbContext and I get error in IdentityDbContext, can't accept class

```
    public class MultiTenantStoreDbContext : EFCoreStoreDbContext<ClientTenantInfo>, IdentityDbContext<ApplicationUser, ApplicationRole, string>
    {
        public MultiTenantStoreDbContext(DbContextOptions<MultiTenantStoreDbContext> options) : base(options)
        {
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            new TenantInfoConfiguration(modelBuilder.Entity<ClientTenantInfo>());
            base.OnModelCreating(modelBuilder);
        }

        public DbSet<ClientTenantInfo> ClientTenantInfos { get; set; }
    }
```

**Comment by AndrewTriesToCode** [comment]
hi, in C# you can only inherit from one class and here you are inheriting from both `EFCoreStoreDbContext<T>` and `IdentityDbContext<TUser, TRole, string>` so I think that is why you are getting the error.

Are you sure you want your tenant store to be part of the same model as Identity?

**Comment by solopromiguel** [comment]
> hi, in C# you can only inherit from one class and here you are inheriting from both `EFCoreStoreDbContext<T>` and `IdentityDbContext<TUser, TRole, string>` so I think that is why you are getting the error.
> 
> Are you sure you want your tenant store to be part of the same model as Identity?

then it would be advisable to separate it

**Comment by AndrewTriesToCode** [comment]
I'm going to make it so the EFCoreStore template expects an interface instead of a class because I there are cases where it makes sense to keep it in one data model. I will get that out in the next few days.

**Comment by solopromiguel** [comment]
> I'm going to make it so the EFCoreStore template expects an interface instead of a class because I there are cases where it makes sense to keep it in one data model. I will get that out in the next few days.

Investigating user management is a microservice, The projects take their identity server apart, which is common for all microservices, but it would also be logical to keep them in the same data model. I will be attentive to that update thanks

**Comment by AndrewTriesToCode** [comment]
So this is trickier than I initially thought. I still plan to improve it but I recommend that if you want to make this work inherit from `IMultiTenantStore<T>` instead of `EFCoreStoreDbContext<T>` and register it using `WithStore<T>`. Then  just implement the store methods yourself -- basically copy from `EFCoreStoreDbContext<T>`. That way you can have your identity db context also be your tenant store. Good luck and let me know how it goes!

**Comment by goforebroke** [comment]
> So this is trickier than I initially thought. I still plan to improve it but I recommend that if you want to make this work inherit from `IMultiTenantStore<T>` instead of `EFCoreStoreDbContext<T>` and register it using `WithStore<T>`. Then just implement the store methods yourself -- basically copy from `EFCoreStoreDbContext<T>`. That way you can have your identity db context also be your tenant store. Good luck and let me know how it goes!

Andrew,

Are you saying the implementation should look like below?

` public class AppDbContextStore : MultiTenantIdentityDbContext<AppUser, AppRole, int>, IMultiTenantStore<MyTenantInfo>`

```
// DbSet for TenantInfo
public DbSet<MyTenantInfo> MyTenants{ get; set; }
```

then you would override the OnModelCreating?

```
modelBuilder.Entity<MyTenantInfo>().HasKey(ti => ti.Id);
modelBuilder.Entity<MyTenantInfo>().Property(ti => ti.Id).HasMaxLength(64);
modelBuilder.Entity<MyTenantInfo>().HasIndex(ti => ti.Identifier).IsUnique();
```


Satisfy all the IMultiTenantStore interface requirements like the code in [EFCoreStore](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/f02be2508e615a4a366b61fd06d5a9d40ec2372c/src/Finbuckle.MultiTenant.EntityFrameworkCore/Stores/EFCoreStore/EFCoreStore.cs)

```
public async Task<bool> TryUpdateAsync(MyTenantInfo tenantInfo)
{
     var existingLocal = MyTenants.Local.Where(ti => ti.Id == tenantInfo.Id).SingleOrDefault();
     if (existingLocal != null)
     {
          Entry(existingLocal).State = EntityState.Detached;
     }

     MyTenants.Update(tenantInfo);
     return await SaveChangesAsync() > 0;
 }
```

Then register the new store in your startup?

```
services.AddMultiTenant<MyTenantInfo>()
.WithStore<AppDbContextStore>(ServiceLifetime.Scoped)
.WithRouteStrategy();
```

When I complete the steps above, I get an error from DI unable to resolve the service type

```
System.InvalidOperationException: Unable to resolve service for type 'Finbuckle.MultiTenant.ITenantInfo' while attempting to activate 'Infrastructure.TenantStore.AppDbContextStore'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.FinbuckleMultiTenantBuilder`1.<>c__DisplayClass7_0`1.<WithStore>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.FinbuckleMultiTenantBuilder`1.<>c__DisplayClass8_0`1.<WithStore>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.FinbuckleServiceCollectionExtensions.<>c__0`1.<AddMultiTenant>b__0_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Finbuckle.MultiTenant.AspNetCore.MultiTenantMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
What am I missing or doing incorrectly

Thx Jaime

**Comment by AndrewTriesToCode** [comment]
Hi Jaime,
you are on the right track. I think what's happening is your `AppDbContextStore` is getting injected in the middleware as an `IMultiTenantStore<T>` to be used as part of the tenant resolution (to determine the correct `ITenantInfo` for the request) in the middleware. Problem is the injection of `AppDbContextStore` needs a `ITenantInfo` so it's a chicken and egg problem. You can see where the injection of all the stores is happening here:
https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/01a6dade0713aaf132af10798e024b20b0e45db1/src/Finbuckle.MultiTenant/TenantResolver.cs#L22-L29

So the constructor of `AppDbContextStore` needs some sort of `ITenantInfo` (this was a design decision on my part for `MultiTenantIdentityDbContext`, but I should reconsider this) but when acting as the tenant store it doesn't really need *the* current `ITenantInfo`. There is an override of `WithStore` that allows you to supply constructor parameters. I suggest you supply a dummy `ITenantInfo` with only the appropriate connection string. It would look something like this:
```cs
...WithStore<AppDbContextStore>(new TenantInfo{ ConnectionString = "abc123" });
```
Does that make sense? Let me know how it goes!

**Comment by goforebroke** [comment]
Andrew,

I made the changes you suggested and this is what I came up with and so far and its working.

In my extension class called from startup

```
// Add Tenant Services
services.AddMultiTenant<MyTenantInfo>()
.WithStore<AppStoreDbContext>(ServiceLifetime.Scoped, new TenantInfo { ConnectionString = config.GetConnectionString("DefaultConnection")})
.WithRouteStrategy();
```

and I modified my constructor in the AppStoreDbContext class.

```
public AppStoreDbContext(ITenantInfo tenantInfo) : base(tenantInfo)
{
}

public AppStoreDbContext(ITenantInfo tenantInfo, DbContextOptions options) : base(tenantInfo, options)
{
}
```

I was able to create an initial migration, create the database with the tenant, identity, and my custom tables. I still need more testing, but so far the initial results are good. I will know more in the next few weeks. I will post back if I run into issues

Again thanks for your help and thx for making Finbuckle.

Jaime
