### ISSUE TITLE
6.4.1 InvalidOperationException in Authentication

### ISSUE THREAD

**Issue by natelaff** [Finbuckle/Finbuckle.MultiTenant#481]
6.4.0 works fine in my code, but updating to 6.4.1 broke things. Haven't dug into this fully yet but can confirm something is going wrong here in this version.

      An unhandled exception has occurred while executing the request.
      Finbuckle.MultiTenant.MultiTenantException: Exception in Finbuckle.MultiTenant.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync.
       ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.InvalidOperationException: Provide Authority, MetadataAddress, Configuration, or ConfigurationManager to OpenIdConnectOptions
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
         at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
         at Finbuckle.MultiTenant.Options.MultiTenantOptionsFactory`2.Create(String name)
         at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
         at Finbuckle.MultiTenant.Options.MultiTenantOptionsCache`2.GetOrAdd(String name, Func`1 createOptions)
         at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
         --- End of inner exception stack trace ---
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Finbuckle.MultiTenant.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync(Object context)
         at Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(Object context)
         --- End of inner exception stack trace ---
         at Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(Object context)
         at Finbuckle.MultiTenant.TenantResolver`1.ResolveAsync(Object context)
         at Finbuckle.MultiTenant.TenantResolver`1.Finbuckle.MultiTenant.ITenantResolver.ResolveAsync(Object context)
         at Finbuckle.MultiTenant.AspNetCore.MultiTenantMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by natelaff** [comment]
Hmm. Looks like it's related to the Configuration changes you made in MultiTenantOptionsFactory perhaps?

**Comment by natelaff** [comment]
Found it. Needed that
options.Authority = "https://__invalid"; // Needed for validation, will be overwritten per-tenant.

**Comment by AndrewTriesToCode** [comment]
Yes this bit me on one of the sample projects. Thanks for submitting the issue regardless.
