### ISSUE TITLE
How to allow WithPerTenantAuthentication to work with IdentityServer's Dynamic Providers?

### ISSUE THREAD

**Issue by acasciani** [Finbuckle/Finbuckle.MultiTenant#548]
Thank you for the awesome project! I am curious what your best practice would be to address an issue with competing registrations for IAuthenticationSchemeProvider? I'm using Duende v6 as the Identity Server and am using Finbuckle's `WithPerTenantAuthentication()` option.

Duende has a dynamic providers feature (for dynamic external SSO configuration) that requires `IAuthenticationSchemeProvider`. I register this first in the startup. The code looks like this:
```
    public static IIdentityServerBuilder AddDynamicProvidersCore(this IIdentityServerBuilder builder)
    {
        builder.Services.AddTransient(svcs => svcs.GetRequiredService<IdentityServerOptions>().DynamicProviders);
        builder.Services.AddTransientDecorator<IAuthenticationSchemeProvider, DynamicAuthenticationSchemeProvider>();
        builder.Services.TryAddSingleton<IIdentityProviderStore, NopIdentityProviderStore>();
        // the per-request cache is to ensure that a scheme loaded from the cache is still available later in the
        // request and made available anywhere else during this request (in case the static cache times out across 
        // 2 calls within the same request)
        builder.Services.AddScoped<DynamicAuthenticationSchemeCache>();

        return builder;
    }
```

Then I register `WithPerTenantAuthentication()` after Duende's is registered. I'm assuming because Finbuckle is registered second, it is overriding Duende's implementation of `IAuthenticationSchemeProvider`.

What is your recommendation to have these work together?

Thank you again!

**Comment by AndrewTriesToCode** [comment]
Hi, you have the correct order. My implementation will decorate the prior one so it will call into the Duende one. I'm not sure if theirs  does this--but I specifically wanted to do this. 

Also integrating with Duende can be tricky. I recommend either the host strategy or BasePathStrategy with app PathBase adjust option set to true. Let me know if you run into any problems. 

Cheers!

**Comment by acasciani** [comment]
So I'm currently using the BasePathStrategy and it's working like a charm. I'm able to login to two separate tenants within the same application. The discovery url is working for each tenant. The only issue I'm getting is when I'm trying to click SSO with an external Identity Provider (e.g. Azure AD).

When I click the link (as an example `https://localhost/__tenant__/External/Challenge?scheme=aad` I receive the following stack trace. On that GET controller, if I breakpoint and check the type registered in dependency injection for IAuthenticationSchemeProvider it is `Finbuckle.MultiTenant.AspNetCore.MultiTenantAuthenticationSchemeProvider`. Is the exception because IAuthenticationSchemeProvider is not registering to `Duende.IdentityServer.Hosting.DynamicProviders.DynamicAuthenticationSchemeProvider`

```
System.InvalidOperationException: No authentication handler is registered for the scheme 'aad'. The registered schemes are: idsrv, idsrv.external, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("aad",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Finbuckle.MultiTenant.AspNetCore.MultiTenantAuthenticationService`1.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 102
   at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Finbuckle.MultiTenant.AspNetCore.MultiTenantMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Also, does your MultiTenantAuthenticationSchemeProvider replace their scheme provider? Does yours provide dynamic schemes?

Thanks!

**Comment by acasciani** [comment]
So I pulled the Finbuckle library into the project with Duende (instead of using the Nuget libraries). I updated the following method in `\src\Finbuckle.MultiTenant.AspNetCore\Extensions\FinbuckleMultiTenantBuilderExtensions.cs`

```
public static FinbuckleMultiTenantBuilder<TTenantInfo> WithPerTenantAuthenticationCore<TTenantInfo>(
    this FinbuckleMultiTenantBuilder<TTenantInfo> builder, Action<MultiTenantAuthenticationOptions>? config = null)
    where TTenantInfo : class, ITenantInfo, new()
    {
        config ??= _ => { };
        builder.Services.Configure(config);

        // We need to "decorate" IAuthenticationService so callbacks so that
        // remote authentication can get the tenant from the authentication
        // properties in the state parameter.
        if (builder.Services.All(s => s.ServiceType != typeof(IAuthenticationService)))
            throw new MultiTenantException(
                "WithPerTenantAuthenticationCore() must be called after AddAuthentication() in ConfigureServices.");
        builder.Services.DecorateService<IAuthenticationService, MultiTenantAuthenticationService<TTenantInfo>>();

        // Replace IAuthenticationSchemeProvider so that the options aren't
        // cached and can be used per-tenant.
        
        //COMMENTING OUT THE FOLLOWING LINES
        //builder.Services.Replace(ServiceDescriptor
        //    .Singleton<IAuthenticationSchemeProvider, MultiTenantAuthenticationSchemeProvider>());

    return builder;
}
```

When I comment out those two lines, everything seems to work okay. Two questions:

1. Will it cause a problem with authentication to comment out the resetting of that DI and using the Duende one instead?
2. Is there a better way to do this? My preference would be to use your Nuget package. Both your `MultiTenantAuthenticationService` and Duende's `DynamicAuthenticationSchemeProvider` are internal classes so I cannot inject them in my custom startup.

**Comment by AndrewTriesToCode** [comment]
Hi sorry I didn't reply sooner. If you are not using separate default authentication schemes per tenant this will be ok. I'm not sure why I use `Services.Replace` there instead of the decorator pattern -- I will see if I can make that change and get a release out soon.

**Comment by acasciani** [comment]
Hi @AndrewTriesToCode - no worries! I ended up forking the project, making a small change to decorate the interface and created PR #551 

So far that change looks to do the trick with our setup

**Comment by AndrewTriesToCode** [comment]
Thanks for contributing! I just put out a patch release for this with your contribution.
