### ISSUE TITLE
Blazor server EF 6 migration failure

### ISSUE THREAD

**Issue by HmichaelG** [Finbuckle/Finbuckle.MultiTenant#570]
Hello,
In the last couple of days I have added Finbuckle Multi-tenant to my app. Everything was working without issue until I attempted and EF Code First migration. My setup is as follows...

1. Separate database strategy
2.  Program.cs...

`var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

//Finbuckle Multi-tenant service
builder.Services.AddMultiTenant<TenantInfo>()
        .WithHostStrategy("__tenant__.*") 
        .WithStaticStrategy("eastlakes")
        .WithConfigurationStore();

// U3ADbContextFactory
builder.Services.AddDbContextFactory<U3ADbContext>(options =>
{
    options.UseSqlServer();
},ServiceLifetime.Scoped);

// Microsoft Core Identity
builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<U3ADbContext>();

...

app.UseWebSockets();
app.UseMultiTenant();
app.UseStaticFiles();

app.UseRouting();

...

`
3. DbContext...

`   public class U3ADbContext : IdentityDbContext<IdentityUser, IdentityRole, string>
    {

        private ITenantInfo TenantInfo { get; set; }

        public U3ADbContext(TenantInfo tenantInfo) {
            // DI will pass in the tenant info for the current request.
            // ITenantInfo is also injectable.
            TenantInfo = tenantInfo;
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            // Use the connection string to connect to the per-tenant database.
            optionsBuilder.UseSqlServer(TenantInfo.ConnectionString);
        }
`
The error I receive when I attempt a migration is ...

`PM> update-database -cont U3ADbContext -project U3A.Database 0
Build started...
Build succeeded.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Finbuckle.MultiTenant.TenantInfo' while attempting to activate 'U3A.Database.U3ADbContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method2(Closure , IServiceProvider , Object[] )
   at Microsoft.EntityFrameworkCore.Internal.DbContextFactorySource`1.<>c__DisplayClass4_0.<CreateActivator>b__1(IServiceProvider p, DbContextOptions`1 _)
   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass23_0.<FindContextFromRuntimeDbContextFactory>b__0()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.`

Thank you

**Comment by AndrewTriesToCode** [comment]
Hi, this issue is usually because at design time there is no actual tenant so when it tries to create the dbcontext it bombs. Check out the docs here for some ideas:
https://www.finbuckle.com/MultiTenant/Docs/v6.7.2/EFCore#design-time-instantiation

**Comment by HmichaelG** [comment]
Andrew
Thank you for your response. I think I achieved a similar result by refactoring my dbContext to be an abstract class with 2 descendants. The migration descendant has a standard constructor while the production descendant has a Finbuckle constructor. Thus far all is good but I'll keep your solution in mind in case I run into issues.

This is my first time using your software and I have to say its been a great pleasure. I still have plenty of testing to do but it suits my purpose perfectly. Again thank you.

MH
