### ISSUE TITLE
How to extend IdentityUser?

### ISSUE THREAD

**Issue by asparatu** [Finbuckle/Finbuckle.MultiTenant#679]
I am trying to extend the IdentityUser using the the preferred way of making new AppUser class and inherent from IdentityUser and adding AppUser class to DbContext.

When I do this way the TenantId column is not created and the unique property is not set. 

When remove the AppUser from the DbContext the table is created with the properties in AppUser class but there is a Discriminator Colum created. I assume this because in the OnModelCreating.
```
modelBuilder.Entity<AppUser>();
```

I didn't see away in the documentation that mentions this.

What would best way to accomplish this?

**Comment by AndrewTriesToCode** [comment]
Hi, what is the base class you are using for your identity db context class? 

There should be a generic one where you specify the user class type that your context will use and that your db context inherits from. You don’t need to register the user class as an entity in the OnModelCreating with this method. 

I’m on my phone at the moment but later I can give you a more specific example if needed.

**Comment by asparatu** [comment]
Hello Andrew,

Here is the code for the ApplicationDbContext

```csharp
public class ApplicationDbContext : MultiTenantIdentityDbContext
{
    public ApplicationDbContext(ITenantInfo tenantInfo) : base(tenantInfo)
    {
    }

    public ApplicationDbContext(ITenantInfo tenantInfo, DbContextOptions options) : base(tenantInfo, options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(TenantInfo.ConnectionString ?? throw new InvalidOperationException());
        base.OnConfiguring(optionsBuilder);
    }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApplicationUser>();
        base.OnModelCreating(modelBuilder);
    }
}
```

Application User
```csharp
public class ApplicationUser : IdentityUser
    {
        [StringLength(50)]
        public string? GivenName { get; set; }

        [StringLength(50)]
        public string? MiddleName { get; set; }

        [StringLength(50)]
        public string? SurName { get; set; }
    }
```

Program.cs
```csharp
builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>();
```

If change the inherits to this:
```csharp
public class ApplicationDbContext : MultiTenantIdentityDbContext<ApplicationUser>
{
}
```
Does not work. It will create with properties from ApplicationUser but not add the TenantId

If change the Program.cs to this same results.
```csharp
builder.Services.AddDefaultIdentity<ApplicaitonUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>();
```

**Comment by AndrewTriesToCode** [comment]
Buried in the docs is this which I think will help:

Deriving from `MultiTenantIdentityDbContext<TUser>` will use the provided parameter for `TUser` and the defaults for the rest. `TUser` will not be configured as multitenant by default. All other entity types will be configured as multitenant.

So you can use your custom user with the db context by deriving from `MultiTenantIdentityDbContext<TUser>` then:

- Add the '[MultiTenant]' data attribute to the entity type class, or
- use the 'IsMultiTenant' fluent api method in 'OnModelCreating' after calling the base class 'OnModelCreating' method (to ensure the Identity model exists).

```cs
[MultiTenant]
public class ApplicationUser : IdentityUser
{
...
}

public class ApplicationDbContext : MultiTenantIdentityDbContext<ApplicationUser>
{
...
}

**Comment by asparatu** [comment]
Hello Andrew,

I will try to add the Add the '[MultiTenant]' data attribute to the entity type class.

I know of try to add 'IsMultiTenant' using fluent API, it will cause error when I try to  migration. This was the first solutions I tried.

**Comment by AndrewTriesToCode** [comment]
Ok but note that your db context is deriving from `MultiTenantIdentityDbContext` but per above should be deriving from `MultiTenantIdentityDbContext<ApplicationUser>`.

**Comment by asparatu** [comment]
If add the '[MultiTenant]' data attribute to the entity type class there are no problems with doing the migration.

Program.cs
```csharp
builder.Services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>();
```

ApplicatinUser.cs
```cshap
[MultiTenant]
public class ApplicationUser : IdentityUser
    {
    }
```

ApplicationDbContext.cs
```csharp
public class ApplicationDbContext : MultiTenantIdentityDbContext<ApplicationUser>
{
}
```

This will create the table correctly, if remove the data attribute and just use the OnModelCreating
```csharp
 protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApplicationUser>().IsMultiTenant();
        base.OnModelCreating(modelBuilder);
    }
```
This error given
```
System.InvalidOperationException: The indexes {'NormalizedUserName', 'TenantId'} on 'ApplicationUser' and {'NormalizedUserName'} on 'ApplicationUser' are both mapped to 'AspNetUsers.UserNameIndex', but with different columns ({'NormalizedUserName', 'TenantId'} and {'NormalizedUserName'}).
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalIndexExtensions.AreCompatible(IReadOnlyIndex index, IReadOnlyIndex duplicateIndex, StoreObjectIdentifier& storeObject, Boolean shouldThrow)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateCompatible(IIndex index, IIndex duplicateIndex, String indexName, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.ValidateCompatible(IIndex index, IIndex duplicateIndex, String indexName, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedIndexesCompatibility(IReadOnlyList`1 mappedTypes, StoreObjectIdentifier& storeObject, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope service   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The indexes {'NormalizedUserName', 'TenantId'} on 'ApplicationUser' and {'NormalizedUserName'} on 'ApplicationUser' are both mapped to 'AspNetUsers.UserNameIndex', but with different columns ({'NormalizedUserName', 'TenantId'} and {'NormalizedUserName'}).
```

I will just add the data attribute to the class entity. I am not sure if this happens with other tables or just the IdentityUsers

**Comment by AndrewTriesToCode** [comment]
It’s because the base class on modeling needs to run before your call to IsMultiTenant because the entity doesn’t exist until the base class sets it up.

**Comment by asparatu** [comment]
Ok, I understand.

Thank you

**Comment by asparatu** [comment]
Hello Andrew,

I have one more issue I can not understand how to fix. When the AddMultiTenant<TenantInfo>() has WithBasePathStrategy(options => options.RebaseAspNetCorePathBase = true) that paths work for the registration and login per tenant but if WithHostStrategy() it does not work.

When try to go to https://tenant.localhost/identity/account/login gives me a 404 error. I do have a tenant.localhost in the host file, so that is not the issue.

I dont know if this might be causing it but changed the database to use MsSql Server. I didnt get an error and did the migration correctly

I know this work but this is not for multi-tenant accounts but for normal identity setup.
```csharp
      services.ConfigureApplicationCookie(o => o.LoginPath = "/login");
      services.ConfigureApplicationCookie(o => o.LogoutPath = "/logout");
      services.ConfigureApplicationCookie(o => o.AccessDeniedPath = "/Account/AccessDenied");
```

I did read the ITenantInfo implements the specific paths but not working. Is there aways to make specific like in the code above?

Program.cs
```csharp
using Finbuckle.MultiTenant;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using IdentitySample.Data;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddDbContext<ApplicationDbContext>();
builder.Services.AddDatabaseDeveloperPageExceptionFilter();

builder.Services.AddIdentity<ApplicationUser, IdentityRole>(opts =>
    {
        opts.SignIn.RequireConfirmedAccount = true;
    })
    .AddEntityFrameworkStores<ApplicationDbContext>();

builder.Services.AddRazorPages();

// Add MultiTenant
builder.Services.AddMultiTenant<TenantInfo>()
    .WithHostStrategy()
    .WithConfigurationStore()
    .WithPerTenantAuthentication();

var app = builder.Build();

// Apply migrations if needed
var store = app.Services.GetRequiredService<IMultiTenantStore<TenantInfo>>();
foreach (var tenant in await store.GetAllAsync())
{
    await using var db = new ApplicationDbContext(tenant);
    await db.Database.MigrateAsync();
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseMigrationsEndPoint();
}
else
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseMultiTenant();
app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapRazorPages();

app.Run();
``` 

I did try adding this code but resulted in a compile-time error
```csharp
        services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
            .AddCookie()
            .AddOpenIdConnect();
```
