### ISSUE TITLE
PK adjustment for IdentityUserRole (AspNetUserRoles)

### ISSUE THREAD

**Issue by Leon99** [Finbuckle/Finbuckle.MultiTenant#849]
Looks like `MultiTenantIdentityDbContext` doesn't add `TenantId` to `PK_AspNetUserRoles`. Is it intended, and if so, why?
The workaround should be as trivial as calling `.AdjustKeys(builder)` for the `IdentityUserRole` but it's internal so its code has to be copied to `OnModelCreating` of the `MultiTenantIdentityDbContext` inheritor, which is not ideal.

**Comment by Leon99** [comment]
Looks like I've got the answer:
```
System.ArgumentException: Entity type 'IdentityUserRole<Guid>' is defined with a 3-part composite key, but 2 values were passed to the 'Find' method.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.ValidateKeyPropertiesAndExtractCancellationToken(Object[] keyValues, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindUserRoleAsync(TKey userId, TKey roleId, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.IsInRoleAsync(TUser user, String normalizedRoleName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.AddToRoleAsync(TUser user, String role)
```
So, effectively, I need to reimplement UserStore and pass tenantId in addition to userId & roleId?

**Comment by AndrewTriesToCode** [comment]
Yeah you are seeing some of the limits of trying to tack on the tenantId column to these data models. Unfortunately there are a few methods in `UserManager` and `UserStore` and their role equivalents that use `Find` on `DbSet` which is problematic. Implementing your own classes which adjust just those cases is feasible. I’m planning to overhaul Identity support to address these but it’s still a ways off.

**Comment by Leon99** [comment]
I got it to work. Not much additional code but took some time to figure out why it's not working out of the box. Would you be interested in a PR with the missing pieces?
