### ISSUE TITLE
System.InvalidOperationException: 'Unable to track an entity of type 'IdentityUserLogin<string>' because its primary key property 'TenantId' is null.'

### ISSUE THREAD

**Issue by MayurPatel-BlobStation** [Finbuckle/Finbuckle.MultiTenant#881]
### Discussed in https://github.com/Finbuckle/Finbuckle.MultiTenant/discussions/879

<div type='discussions-op-text'>

<sup>Originally posted by **MayurPatel-BlobStation** October  4, 2024</sup>
"When I attempt to insert data into the AspNetUserLogin table, I encounter the following error: System.InvalidOperationException: 'Unable to track an entity of type 'IdentityUserLogin<string>' because its primary key property 'TenantId' is null.'. However, inserting data into the AspNetUser table works correctly."

  var userResult = await _userManager.FindByEmailAsync("abc@gmail.com");
  var result = await _userManager.AddLoginAsync(userResult, externalLoginInfo);</div>

**Comment by AndrewTriesToCode** [comment]
Thanks I am looking into it. Does this happen during the third party sign in login flow or are you inserting into the table somewhere else in your code?

**Comment by MayurPatel-BlobStation** [comment]
> Thanks I am looking into it. Does this happen during the third party sign in login flow or are you inserting into the table somewhere else in your code?

Yes, In application I am implementing google and Microsoft SSO login, From UI side I have received Google token, so first I have check token is verified or not, if token is verified then check Login exist or not with

var result = await _userManager.FindByLoginAsync(loginProvider,providerKey);

If no login exist then inserting data in AspNetUser table then AspNetUserLogin table. but in AspNetUser data inserted successfully but AspNetUserLogin cause issue.

**Comment by AndrewTriesToCode** [comment]
Are you using Asp.net Identity? Also can you please post what your Finbuckle setup looks like in your program.cs file?

**Comment by MayurPatel-BlobStation** [comment]
Yes I have use Asp.net identity.

program.cs file code :

----------**Program.cs**----------
		 
    builder.Services.AddAppServices(configuration);
    
    var app = builder.Build();
    app.UseMultiTenant();
			
----------**ServiceCollectionExtensions.cs**----------

      public static class ServiceCollectionExtensions
      {
      
            public static void AddAppServices(this IServiceCollection services, ApiConfiguration configuration)
            {
                  services.AddSubscriptionManagmentDbContext(configuration!.DbSettings);
                  services.AddMultiTenantStoreDbContext(configuration!.DbSettings);
                  services.AddMultiTenant<TenantInfo>()
                  .WithRouteStrategy("TenantId")
                  .WithHeaderStrategy("TenantIdKey")
                  .WithPerTenantAuthentication()
                  .WithEFCoreStore<MultiTenantStoreDbContext, TenantInfo>();
            }
      
            public static void AddSubscriptionManagmentDbContext(this IServiceCollection services, DbSettings dbSettings)
            {
                  NpgsqlConnection.GlobalTypeMapper.EnableDynamicJson();
                  services.AddDbContext<SubscriptionManagmentDbContext>(opts =>
                  {
                  opts.UseNpgsql(Convert.ToString(dbSettings.ConnectionString));
                  opts.ConfigureWarnings(w => w.Ignore(RelationalEventId.MultipleCollectionIncludeWarning));
                  });
            }
      
            public static void AddMultiTenantStoreDbContext(this IServiceCollection services, DbSettings dbSettings)
            {
                  services.AddDbContext<MultiTenantStoreDbContext>(opts =>
                  {
                        opts.UseNpgsql(Convert.ToString(dbSettings.ConnectionString));
                        opts.ConfigureWarnings(w => w.Ignore(RelationalEventId.MultipleCollectionIncludeWarning));
                  });
            }
      }


----------**MultiTenantStoreDbContext.cs**----------


`  public class MultiTenantStoreDbContext : EFCoreStoreDbContext<TenantInfo>
{
    public MultiTenantStoreDbContext(DbContextOptions options) : base(options){}
}`

----------SubscriptionManagmentDbContext.cs----------


      public class SubscriptionManagmentDbContext : MultiTenantIdentityDbContext
      {
	      private readonly IMultiTenantContextAccessor _multiTenantContextAccessor;
	      protected readonly IHttpContextAccessor _httpContextAccessor;
	      public SubscriptionManagmentDbContext(DbContextOptions<SubscriptionManagmentDbContext> options, 
                             IMultiTenantContextAccessor multiTenantContextAccessor
        		      , IHttpContextAccessor httpContextAccessor) : base(multiTenantContextAccessor, options)
	      {
		      _multiTenantContextAccessor = multiTenantContextAccessor;
		      _httpContextAccessor = httpContextAccessor;
	      }
      
	      public SubscriptionManagmentDbContext(IMultiTenantContextAccessor multiTenantContextAccessor) : base(multiTenantContextAccessor)
	      {}
      
	      public SubscriptionManagmentDbContext(ITenantInfo tenantInfo, DbContextOptions<SubscriptionManagmentDbContext> options) :
		      base(tenantInfo, options){}
      
	      protected override void OnModelCreating(ModelBuilder modelBuilder)
	      {
		      base.OnModelCreating(modelBuilder);
	      }
      }

**Comment by AndrewTriesToCode** [comment]
Thanks. I don’t see any issues with this code. Where exactly in your app is `AddLoginAsync ` getting called?

**Comment by MayurPatel-BlobStation** [comment]
I have created a repository called IdentityRepository, which I am currently using.

Repository Code:

       public class IdentityRepository : IIdentityRepository
       {
           private readonly UserManager<IdentityUser> _userManager;
           private readonly SignInManager<IdentityUser> _signInManager;
           public IdentityRepository(
               UserManager<IdentityUser> userManager,
               SignInManager<IdentityUser> signInManager,
               )
	      {
               _userManager = userManager;
               _signInManager = signInManager;
	      }
	      
          public async Domains.IdentityUser AddLoginAsync(Domains.IdentityUser users, UserLoginInfo externalLoginInfo)
	      {
		      try
		      {
                var insertUserModel = _mapper.Map<IdentityUser>(users);
                var result = await _userManager.AddLoginAsync(insertUserModel, externalLoginInfo);
		        return _mapper.Map<Domains.IdentityUser>(insertUserModel);
		      }
		      catch(){}
	      }
      }

**Comment by AndrewTriesToCode** [comment]
Is your identity repository registered in DI? What is the lifetime? The user manager internally will have a user store which internally uses your dbcontext which was instantiated for the current tenant. If you also inject `IMultitenantAccessor` into this class does it resolve the correct tenant right before the add user login call?

**Comment by MayurPatel-BlobStation** [comment]
I have registered the identity repository in dependency injection with a scoped lifetime. However, I cannot find `IMultitenantAccessor`, which I believe refers to `IMultiTenantContextAccessor`. Even after using this, it is still not working.

**Comment by ekallaur** [comment]
Points to consider:
- in the MultiTenantIdentityDbContext the PK is changed to include TenantId 
    see `MultiTenantIdentityDbContext<TUser, TRole, TKey> `
   ` builder.Entity<IdentityUserLogin<TKey>>().IsMultiTenant().AdjustUniqueIndexes().AdjustKeys(builder);`
- UserStore creates IdentityUserLogin internally and adds it to the DbContext. TenantId is null at this stage thats why DbContext Add fails

A quick solution is to override Create... methods of the UserStore and RoleStore to ensure that TenantId is specified.
```csharp
services.AddScoped<IRoleStore<IdentityRole>, MultiTenantRoleStore>();
services.AddScoped<IUserStore<IdentityUser>, MultiTenantUserStore>();
services.AddIdentity<IdentityUser, IdentityRole>()
      .AddEntityFrameworkStores<MyMultiTenantIdentityDbContext>()
      .AddDefaultTokenProviders();
```
```csharp			
public sealed class MultiTenantUserStore : UserStore<IdentityUser>
{
    private readonly MyMultiTenantIdentityDbContext _context;

    public MultiTenantUserStore(
        MyMultiTenantIdentityDbContext context,
        IdentityErrorDescriber describer = null)
        : base(context, describer)
    {
        ArgumentNullException.ThrowIfNull(context, nameof(context));
        _context = context;
    }

    protected override IdentityUserClaim<string> CreateUserClaim(IdentityUser user, Claim claim)
    {
        return _context.EnforceMultiTenant(
            base.CreateUserClaim(user, claim));
    }

    protected override IdentityUserRole<string> CreateUserRole(IdentityUser user, IdentityRole role)
    {
        return _context.EnforceMultiTenant(
            base.CreateUserRole(user, role));
    }

    protected override IdentityUserToken<string> CreateUserToken(IdentityUser user, string loginProvider, string name, string value)
    {
        return _context.EnforceMultiTenant(
            base.CreateUserToken(user, loginProvider, name, value));
    }

    protected override IdentityUserLogin<string> CreateUserLogin(IdentityUser user, UserLoginInfo login)
    {
        return _context.EnforceMultiTenant(
            base.CreateUserLogin(user, login));
    }
}
```
```csharp
public sealed class MultiTenantRoleStore : RoleStore<IdentityRole>
{
    private readonly MyMultiTenantIdentityDbContext _context;

    public MultiTenantRoleStore(MyMultiTenantIdentityDbContext context, IdentityErrorDescriber describer = null)
        : base(context, describer)
    {
        ArgumentNullException.ThrowIfNull(context, nameof(context));
        _context = context;
    }

    protected override IdentityRoleClaim<string> CreateRoleClaim(IdentityRole role, Claim claim)
    {
        return _context.EnforceMultiTenant(
            base.CreateRoleClaim(role, claim));
    }
}
```
```csharp
internal static class MultiTenantIdentityDbContextExtensions
{
    private const string TENANT_ID = "TenantId";

    internal static T EnforceMultiTenant<T>(this MultiTenantIdentityDbContext context, T entity)
    {
        var entry = context.Entry(entity);

        if (!entry.Metadata.IsMultiTenant())
        {
            return entity;
        }

        var tenantProperty = entry.Property(TENANT_ID);
        var actualTenant = tenantProperty.CurrentValue;
        var expectedTenant = context.TenantInfo.Id;

        if (actualTenant is null)
        {
            tenantProperty.CurrentValue = expectedTenant;
            return entity;
        }

        if (actualTenant.Equals(context.TenantInfo.Id))
        {
            return entity;
        }

        switch (context.TenantMismatchMode)
        {
            case TenantMismatchMode.Ignore:
            {
                return entity;
            }
            case TenantMismatchMode.Overwrite:
            {
                tenantProperty.CurrentValue = expectedTenant;
                return entity;
            }
            case TenantMismatchMode.Throw:
            {
                throw new MultiTenantException($"Tenant mismatch. Expected {expectedTenant}. Actual {actualTenant}");
            }
            default:
            {
                throw new NotImplementedException($"TenantMismatchMode {context.TenantMismatchMode}. Expected {expectedTenant}. Actual {actualTenant}");
            }
        }
    }
}
```

**Comment by AndrewTriesToCode** [comment]
hi @ekallaur that is a good approach. In the right settings the regular user store should work though. Another option is to set [`TenantNotSet` mode to overwrite](https://www.finbuckle.com/MultiTenant/Docs/v9.1.3/EFCore#tenant-not-set-mode) in which case the db context will set the tenant correctly. Depending on where exactly the user store is called from it can be tricky to ensure the tenant is set correctly when the dbcontext saves the changes, but for most normal situations it is doable.

**Comment by ekallaur** [comment]
> hi [@ekallaur](https://github.com/ekallaur) that is a good approach. In the right settings the regular user store should work though. Another option is to set [`TenantNotSet` mode to overwrite](https://www.finbuckle.com/MultiTenant/Docs/v9.1.3/EFCore#tenant-not-set-mode) in which case the db context will set the tenant correctly. Depending on where exactly the user store is called from it can be tricky to ensure the tenant is set correctly when the dbcontext saves the changes, but for most normal situations it is doable.

hi @AndrewTriesToCode `TenantNotSet` is used in the [EnforceMultiTenant](https://github.com/Finbuckle/Finbuckle.MultiTenant/blob/4cfe73c7d26e1957e8c13211da2f8295f18990ad/src/Finbuckle.MultiTenant.EntityFrameworkCore/Extensions/MultiTenantDbContextExtensions.cs#L17) during `SaveChanges` or `SaveChangesAsync`, but this error happens much earlier - during `Set<T>().Add(entity)` when entity has `TenantId` as a part of PK and `TenantId` is null. see [UserStore.AddLoginAsync](https://github.com/dotnet/aspnetcore/blob/fd3fe12cec7cc0b8b820e414a39fd5cae10abcc2/src/Identity/EntityFrameworkCore/src/UserStore.cs#L485).

The full stack track for clarity of the original issue:
```
System.InvalidOperationException: Unable to track an entity of type 'IdentityUserLogin<string>' because its primary key property 'TenantId' is null.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.AddLoginAsync(TUser user, UserLoginInfo login, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.AddLoginAsync(TUser user, UserLoginInfo login)
   at ThisIsMyProject.AndThisIsMyMethod(ExternalUser user) in PathToFile.cs:line 45
```

**Comment by AndrewTriesToCode** [comment]
Yeah you are right. I’m looking further into this.

**Comment by AndrewTriesToCode** [comment]
Ok after digging in I have come to the conclusion that adding the PK to that table is more trouble than it is worth. I’ll put out a new release to remove that this week. The original idea was that table doesn’t have a guid ID like the others but after examining how it is used by UserManager and UserStore I don’t think it’s needed.

**Comment by ekallaur** [comment]
@AndrewTriesToCode just for the record: 
- when UserLogin PK has no TenantId and the same external IdP is used for different tenants, then the error occur during add UserLogin - duplicate PK.

**Comment by AndrewTriesToCode** [comment]
@ekallaur that could be an issue but I examined the `UserStore` class carefully and I believe everywhere where it tries to query there is an implicit "where tenantId = _tenantid_" added so there is little risk. I'd like to have the PK still but I can't figure out how to have it set with having to provide a shim implementation of `UserManager` which I may end up doing in the future.

**Comment by AndrewTriesToCode** [comment]
This fix was just released, hope this lets you move on to 9.x

**Comment by AndrewTriesToCode** [comment]
In v10 this should be resolved via the `EnforceMultiTenantTracking` method that can be called on the db context instance after construction.

**Comment by AndrewTriesToCode** [comment]
I'm going to close this issue out because I believe this issue is fixed in the code now for some time. Can always reopen if needed.
