### ISSUE TITLE
WithRouteStrategy, AddOpenIdConnect callback error, how to fix

### ISSUE THREAD

**Issue by sisindrymedagam** [Finbuckle/Finbuckle.MultiTenant#907]
Hi I am using WithRouteStrategy and below is my configuration

```cs
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

 IConfiguration Configuration = builder.Configuration;

 builder.Services.AddAuthentication(o =>
 {
     o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
     o.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
 })
.AddCookie(options =>
{
    options.AddCookieAuthenticationOptions();
})
.AddOpenIdConnect();

 builder.Services.AddMultiTenant<TrisoftTenantInfo>()
     .WithRouteStrategy()
     .WithEFCoreStore<TenantStoreDbContext, TrisoftTenantInfo>()
     .WithPerTenantAuthentication();

 builder.Services.ConfigurePerTenant<CookieAuthenticationOptions, TrisoftTenantInfo>(CookieAuthenticationDefaults.AuthenticationScheme, (options, tenantInfo) =>
 {
     options.AddCookieAuthenticationOptions();

     options.Cookie.Path = tenantInfo.Identifier;
     options.Cookie.Name = "Cookie-" + tenantInfo.Identifier;
 });

 builder.Services.ConfigurePerTenant<OpenIdConnectOptions, TrisoftTenantInfo>(OpenIdConnectDefaults.AuthenticationScheme, (options, tenantInfo) =>
 {
     //https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/samples/OpenIdConnectSample/Startup.cs
     options.ClientId = tenantInfo.Identifier;
     options.ClientSecret = tenantInfo.ClientSecretPlain;
     options.Authority = Configuration["Links:Authority"];
     options.ClaimsIssuer = Configuration["Links:Issuer"];
     options.ResponseType = OpenIdConnectResponseType.Code;

     options.Scope.Add("openid");
     options.Scope.Add("email");
     options.Scope.Add("profile");
     options.Scope.Add("roles");
     options.CallbackPath = $"/{tenantInfo.Identifier}/signin-oidc";
     options.SignedOutCallbackPath = $"/{tenantInfo.Identifier}/signout-callback-oidc";

     options.GetClaimsFromUserInfoEndpoint = true;

     options.Events = new OpenIdConnectEvents
     {
         OnUserInformationReceived = async context =>
         {
             System.Text.Json.JsonElement userInfo = context.User.RootElement;

             string? image = userInfo.GetString("image");

             Dictionary<string, string> allClaims = userInfo.EnumerateObject()
                 .ToDictionary(p => p.Name, p => p.Value.ToString());

             // Add custom claims to the identity
             ClaimsIdentity? identity = context?.Principal?.Identity as ClaimsIdentity;

             identity?.AddClaim(new Claim("image", image ?? ""));

             await Task.CompletedTask;
         },
         OnTokenValidated = async context =>
         {
             ClaimsIdentity? identity = context?.Principal?.Identity as ClaimsIdentity;

             if (identity != null && !identity.IsAuthenticated)
             {
                 context?.HandleResponse();
                 context?.Response.Redirect("/Home/Error?message=User is not authenticated.");
             }
             else
             {
                 string? audience = identity?.FindFirst(Claims.Audience)?.Value;
                 string? name = identity?.FindFirst(Claims.Name)?.Value;

                 identity?.AddClaim(new Claim(Claims.Audience, audience ?? ""));
                 identity?.AddClaim(new Claim(ClaimTypes.GivenName, name ?? ""));
             }
             await Task.CompletedTask;
         }
     };
 });


WebApplication app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/error");
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.UseMultiTenant();

app.UseAuthentication();

app.UseAuthorization();

app.MapControllerRoute("default", "{__tenant__}/{controller=Home}/{action=Index}/{id?}");

//await app.AddTenantStoreAsync(); //Add tenants to finbuckle

app.Run();
```

I am getting the below error after successful authentication from the identity server(without any route strategy I am successfully log in to the application) below are the exception details

```
An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null. (Parameter 'ClientId')
System.ArgumentNullException.Throw(string paramName)

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MethodBaseInvoker.InvokeWithOneArg(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)

MultiTenantException: Exception in Finbuckle.MultiTenant.AspNetCore.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync.
Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(object context)

Stack Query Cookies Headers Routing
ArgumentNullException: Value cannot be null. (Parameter 'ClientId')
System.ArgumentNullException.Throw(string paramName)
System.ArgumentNullException.ThrowIfNull(object argument, string paramName)
System.ArgumentException.ThrowNullOrEmptyException(string argument, string paramName)
System.ArgumentException.ThrowIfNullOrEmpty(string argument, string paramName)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(string scheme)
Microsoft.AspNetCore.Authentication.AuthenticationBuilder+<>c__DisplayClass4_0<TOptions, THandler>.<AddSchemeHelper>b__1(TOptions o)
Microsoft.Extensions.Options.ValidateOptions<TOptions>.Validate(string name, TOptions options)
Microsoft.Extensions.Options.OptionsFactory<TOptions>.Create(string name)
System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
System.Lazy<T>.CreateValue()
Finbuckle.MultiTenant.Options.MultiTenantOptionsCache<TOptions>.GetOrAdd(string name, Func<TOptions> createOptions)
InvokeStub_IOptionsMonitor`1.Get(object , Span<object> )
System.Reflection.MethodBaseInvoker.InvokeWithOneArg(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)

Show raw exception details
System.ArgumentNullException: Value cannot be null. (Parameter 'ClientId')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
   at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Finbuckle.MultiTenant.Options.MultiTenantOptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at InvokeStub_IOptionsMonitor`1.Get(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MethodBaseInvoker.InvokeWithOneArg(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
System.Reflection.MethodBase.Invoke(object obj, object[] parameters)
Finbuckle.MultiTenant.AspNetCore.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync(object context)
Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(object context)

Show raw exception details
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'ClientId')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
   at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Finbuckle.MultiTenant.Options.MultiTenantOptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at InvokeStub_IOptionsMonitor`1.Get(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Finbuckle.MultiTenant.AspNetCore.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync(Object context)
   at Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(Object context)
MultiTenantException: Exception in Finbuckle.MultiTenant.AspNetCore.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync.
Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(object context)
Finbuckle.MultiTenant.TenantResolver<TTenantInfo>.ResolveAsync(object context)
Finbuckle.MultiTenant.TenantResolver<TTenantInfo>.Finbuckle.MultiTenant.Abstractions.ITenantResolver.ResolveAsync(object context)
Finbuckle.MultiTenant.AspNetCore.Internal.MultiTenantMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

Show raw exception details
Finbuckle.MultiTenant.MultiTenantException: Exception in Finbuckle.MultiTenant.AspNetCore.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'ClientId')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
   at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Finbuckle.MultiTenant.Options.MultiTenantOptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at InvokeStub_IOptionsMonitor`1.Get(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Finbuckle.MultiTenant.AspNetCore.Strategies.RemoteAuthenticationCallbackStrategy.GetIdentifierAsync(Object context)
   at Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(Object context)
   --- End of inner exception stack trace ---
   at Finbuckle.MultiTenant.Strategies.MultiTenantStrategyWrapper.GetIdentifierAsync(Object context)
   at Finbuckle.MultiTenant.TenantResolver`1.ResolveAsync(Object context)
   at Finbuckle.MultiTenant.TenantResolver`1.Finbuckle.MultiTenant.Abstractions.ITenantResolver.ResolveAsync(Object context)
   at Finbuckle.MultiTenant.AspNetCore.Internal.MultiTenantMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by AndrewTriesToCode** [comment]
Hi, looks like for whatever reason client Id is null coming out of the options creation. 

Internally the tenant strategy has to create an instance of the  OpenID connect options to know the endpoint—but when it does so the options validation that says client id can’t be null fails.

In your open id connect options configuration set a non null dummy value so that options validation doesn’t fail. On any real request the dummy will get overridden by the per tenant options.

**Comment by sisindrymedagam** [comment]
Hi @AndrewTriesToCode can you provide some code here please. In my tenant store the identifier always has a value. 
Thanks

**Comment by AndrewTriesToCode** [comment]
I’m can provide code tomorrow but basically in `AddOpenIdConnect` you’ll want to set options to set valid values for options generated when no tenant is in context — when creating the options as a part of the remote authentication  strategy there is not yet a tenant because the strategy hasn’t resolved it yet.

**Comment by sisindrymedagam** [comment]
Understand, I will check and update you. Thank you

**Comment by sisindrymedagam** [comment]
Thanks, @AndrewTriesToCode, Here is my working updated config. 
Here is my question: How can I validate whether a user belongs to a specific tenant? I plan to use the `OnTokenValidated` event in `OpenIdConnectEvents`, but I'm open to suggestions for alternative approaches with code samples.

```CS
 IConfiguration Configuration = builder.Configuration;

 builder.Services.AddAuthentication(options =>
 {
     options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
     options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
 })
.AddCookie(options =>
{
    options.AddCookieAuthenticationOptions();
})
.AddOpenIdConnect(options =>
{
    //https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/samples/OpenIdConnectSample/Startup.cs
    //These are the default options for the tenant, we can override the options in ConfigurePerTenant<OpenIdConnectOptions, TrisoftTenantInfo>
    options.ClientId = "tenant";
    options.ClientSecret = "tenant";
    options.Authority = Configuration["Links:Authority"];
    options.ClaimsIssuer = Configuration["Links:Issuer"];
    options.ResponseType = OpenIdConnectResponseType.Code;

    options.Scope.Add("openid");
    options.Scope.Add("email");
    options.Scope.Add("profile");
    options.Scope.Add("roles");

    options.GetClaimsFromUserInfoEndpoint = true;

    options.Events = new OpenIdConnectEvents
    {
        //There are other events can be fiund here https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectevents?view=aspnetcore-9.0
        OnTokenValidated = async context =>
        {
            //Triggered after the tokens(ID token, access token) have been successfully validated. This is a common place to add or manipulate user claims.
            //Use Cases:
            //Performing additional validation on the tokens like tenant validation, user exists in the tenant.
            //Adding custom claims to the user’s principal.
            ClaimsIdentity? identity = context?.Principal?.Identity as ClaimsIdentity;

            if (identity != null && !identity.IsAuthenticated)
            {
                context?.HandleResponse();
                context?.Response.Redirect("/Home/Error?message=User is not authenticated.");
            }
            else
            {
                string? audience = identity?.FindFirst(Claims.Audience)?.Value;
                string? name = identity?.FindFirst(Claims.Name)?.Value;

                identity?.AddClaim(new Claim(Claims.Audience, audience ?? ""));
                identity?.AddClaim(new Claim(ClaimTypes.GivenName, name ?? ""));
            }
            await Task.CompletedTask;
        },
        OnUserInformationReceived = async context =>
        {
            //Triggered when user information is retrieved from the IdP’s userinfo endpoint.
            //Use Cases:
            //Adding claims from the userinfo response to the user’s identity.
            //Logging or processing additional user information.
            System.Text.Json.JsonElement userInfo = context.User.RootElement;

            string? image = userInfo.GetString("image");

            Dictionary<string, string> allClaims = userInfo.EnumerateObject()
                .ToDictionary(p => p.Name, p => p.Value.ToString());

            ClaimsIdentity? identity = context?.Principal?.Identity as ClaimsIdentity;

            identity?.AddClaim(new Claim("image", image ?? ""));

            await Task.CompletedTask;
        },
        OnAuthenticationFailed = context =>
        {
            //Triggered when authentication fails for any reason, such as invalid tokens or a mismatch in state values.
            //Use Cases:
            //Logging authentication errors.
            //Redirecting users to a custom error page.
            context.Response.Redirect("/Home/Error?message=" + context.Exception.Message);
            context.HandleResponse(); // Prevent further processing
            return Task.CompletedTask;
        },
        OnRemoteFailure = context =>
        {
            //Triggered when there is a failure in the remote authentication process(e.g., a network issue or IdP error).
            //Use Cases:
            //Logging errors related to remote authentication.
            //Redirecting users to a fallback page.
            context.Response.Redirect("/Home/ExternalError?message=" + context.Failure?.Message);
            context.HandleResponse();
            return Task.CompletedTask;
        }
    };
});

 builder.Services.AddMultiTenant<TrisoftTenantInfo>()
     .WithRouteStrategy()
     .WithRemoteAuthenticationCallbackStrategy()
     .WithEFCoreStore<TenantStoreDbContext, TrisoftTenantInfo>()
     .WithPerTenantAuthentication();

 builder.Services.ConfigurePerTenant<CookieAuthenticationOptions, TrisoftTenantInfo>(CookieAuthenticationDefaults.AuthenticationScheme, (options, tenantInfo) =>
 {
     options.AddCookieAuthenticationOptions();

     options.Cookie.Path = $"/{tenantInfo.Identifier}";
     options.Cookie.Name = "Cookie-" + tenantInfo.Identifier;
 });

 builder.Services.ConfigurePerTenant<OpenIdConnectOptions, TrisoftTenantInfo>(OpenIdConnectDefaults.AuthenticationScheme, (options, tenantInfo) =>
 {
     options.ClientId = tenantInfo.Identifier;
     options.ClientSecret = tenantInfo.ClientSecretPlain;
 });
```

Thank you,
SISI

**Comment by sisindrymedagam** [comment]
Hi @AndrewTriesToCode 
Here is my question: How can I validate whether a user belongs to a specific tenant? I plan to use the `OnTokenValidated` event in `OpenIdConnectEvents`, but I'm open to suggestions for alternative approaches with code samples.

**Comment by AndrewTriesToCode** [comment]
If you are using `WithPerTenantAuthentication` it will add the tenant active at the time of sign in to the properties collection of the sign in context. It then also sets up authentication validation events that checks during later authentication that the current tenant matches the saved tenant at the time of authentication. 

Does that cover your use case? If you need to access this property yourself you can call `AuthenticateAsync` again on the `HttpContext` or even better use `IAuthenticationResultFeature`.

**Comment by sisindrymedagam** [comment]
Got it thanks @AndrewTriesToCode
